# -*- coding: utf-8 -*-
"""RFI_Detection_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18227isDx5hQwTTzb4VGP3O6eCh0y8wq8

Title: Detection of Radio Frequency Interference Affecting Soil Moisture Retrieval Quality in NASA’s SMAP Passive Microwave Observations: A Comparative Study Using an Advanced Machine Learning Framework


Student: Zahid Hasan Shovon
UB Number: 25032949
COS7045-B Advanced Machine Learning
MSc Satellite Systems Engineering
University of Bradford

Date: 27 April 2026

Install packages

Install all required libraries
"""

!pip -q install xgboost plotly shap umap-learn kaleido openpyxl

"""Import all libraries"""

import os
import warnings
warnings.filterwarnings("ignore")

import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import shap
import xgboost as xgb
import umap.umap_ as umap
import tensorflow as tf

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV,
    cross_val_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    precision_recall_curve
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.inspection import permutation_importance

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, GlobalAveragePooling1D
from tensorflow.keras.callbacks import EarlyStopping

pio.renderers.default = "colab"

print("All libraries loaded.")

"""Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""Set paths"""

file_path = "/content/drive/MyDrive/AML/Data/SMAP_L1B_TB_59906_A_20260419T160238_R19240_001.h5"
output_dir = "/content/drive/MyDrive/AML/Outputs"
os.makedirs(output_dir, exist_ok=True)

print("Input exists:", os.path.exists(file_path))
print("Output folder:", output_dir)

"""Inspect HDF5 structure"""

with h5py.File(file_path, "r") as f:
    def print_name(name):
        print(name)
    f.visit(print_name)

"""Extract variables - Extracting the main radiometric, geolocation, quality, and timing variables used for analysis and modelling."""

with h5py.File(file_path, "r") as f:
    tb_h = f["Brightness_Temperature/tb_h"][:]
    tb_v = f["Brightness_Temperature/tb_v"][:]
    tb_lat = f["Brightness_Temperature/tb_lat"][:]
    tb_lon = f["Brightness_Temperature/tb_lon"][:]
    incidence = f["Brightness_Temperature/earth_boresight_incidence"][:]
    nedt_h = f["Brightness_Temperature/nedt_h"][:]
    nedt_v = f["Brightness_Temperature/nedt_v"][:]
    qual_flag_h = f["Brightness_Temperature/tb_qual_flag_h"][:]
    tb_time_seconds = f["Brightness_Temperature/tb_time_seconds"][:]

print("tb_h:", tb_h.shape)
print("tb_v:", tb_v.shape)
print("tb_lat:", tb_lat.shape)
print("tb_lon:", tb_lon.shape)
print("incidence:", incidence.shape)
print("nedt_h:", nedt_h.shape)
print("nedt_v:", nedt_v.shape)
print("qual_flag_h:", qual_flag_h.shape)
print("tb_time_seconds:", tb_time_seconds.shape)

"""Quick preview"""

print("tb_h sample:", tb_h.flatten()[:10])
print("tb_v sample:", tb_v.flatten()[:10])
print("tb_lat sample:", tb_lat.flatten()[:10])
print("tb_lon sample:", tb_lon.flatten()[:10])
print("incidence sample:", incidence.flatten()[:10])
print("qual_flag_h unique values:", np.unique(qual_flag_h.flatten())[:20])

"""Build dataframe

Convert the extracted arrays into a tabular pandas DataFrame for cleaning, analysis, and machine learning.
"""

df = pd.DataFrame({
    "tb_h": np.ravel(tb_h),
    "tb_v": np.ravel(tb_v),
    "tb_lat": np.ravel(tb_lat),
    "tb_lon": np.ravel(tb_lon),
    "incidence": np.ravel(incidence),
    "nedt_h": np.ravel(nedt_h),
    "nedt_v": np.ravel(nedt_v),
    "qual_flag_h": np.ravel(qual_flag_h),
    "tb_time_seconds": np.ravel(tb_time_seconds)
})

print(df.shape)
df.head()

"""Clean dataframe

Removing invalid values, missing values, physically impossible coordinates, and sort the data in time order for better sequential modelling.
"""

df = df.replace([np.inf, -np.inf], np.nan)

for col in ["tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v", "tb_time_seconds"]:
    df.loc[np.abs(df[col]) > 1e10, col] = np.nan

df = df.dropna().copy()

df = df[
    (df["tb_lat"] >= -90) & (df["tb_lat"] <= 90) &
    (df["tb_lon"] >= -180) & (df["tb_lon"] <= 180)
].copy()

df = df.sort_values("tb_time_seconds").reset_index(drop=True)

print("Cleaned shape:", df.shape)
df.head()

"""Create target label

Create the binary classification target using the SMAP quality flag, where non-zero indicates quality-affected / potentially RFI-affected observations.
"""

df["target"] = (df["qual_flag_h"] != 0).astype(int)
df["target_label"] = df["target"].map({0: "Clean", 1: "Affected"})

print(df["target"].value_counts())
print(df["target"].value_counts(normalize=True))

"""# FEATURE ENGINEERING

Add engineered features

Creating additional physically motivated and statistically informative features, including brightness temperature difference and local rolling statistics such as kurtosis.
"""

window = 9

df["tb_diff"] = df["tb_h"] - df["tb_v"]

df["tb_h_roll_mean"] = df["tb_h"].rolling(window=window, center=True).mean()
df["tb_v_roll_mean"] = df["tb_v"].rolling(window=window, center=True).mean()

df["tb_h_roll_std"] = df["tb_h"].rolling(window=window, center=True).std()
df["tb_v_roll_std"] = df["tb_v"].rolling(window=window, center=True).std()

df["tb_h_roll_kurt"] = df["tb_h"].rolling(window=window, center=True).kurt()
df["tb_v_roll_kurt"] = df["tb_v"].rolling(window=window, center=True).kurt()
df["tb_diff_roll_kurt"] = df["tb_diff"].rolling(window=window, center=True).kurt()

df = df.dropna().reset_index(drop=True)

print("Shape after feature engineering:", df.shape)
df.head()

"""# EDA

Descriptive statistics
Producing a detailed descriptive statistical summary
"""

stats_cols = [
    "tb_h", "tb_v", "tb_lat", "tb_lon", "incidence",
    "nedt_h", "nedt_v", "tb_diff",
    "tb_h_roll_mean", "tb_v_roll_mean",
    "tb_h_roll_std", "tb_v_roll_std",
    "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"
]

desc = df[stats_cols].describe().T
desc["median"] = df[stats_cols].median()
desc["mode"] = df[stats_cols].mode().iloc[0]
desc["variance"] = df[stats_cols].var()
desc["skewness"] = df[stats_cols].skew()
desc["kurtosis"] = df[stats_cols].kurt()

desc.to_csv(f"{output_dir}/descriptive_statistics.csv")
desc

"""Class distribution charts

Visualising the distribution of clean versus affected observations
"""

class_counts = df["target_label"].value_counts().reset_index()
class_counts.columns = ["Class", "Count"]

fig = px.pie(
    class_counts,
    names="Class",
    values="Count",
    hole=0.45,
    color="Class",
    title="Class Distribution of SMAP Observations"
)
fig.update_traces(textinfo="percent+label")
fig.show()
fig.write_html(f"{output_dir}/class_distribution_donut.html")

fig = px.bar(
    class_counts,
    x="Class",
    y="Count",
    color="Class",
    text="Count",
    title="Class Counts"
)
fig.update_traces(textposition="outside")
fig.show()
fig.write_html(f"{output_dir}/class_distribution_bar.html")

"""Histograms

Examining feature distributions by class and assess whether the two classes differ in their ranges and shapes.
"""

for col in ["tb_h", "tb_v", "incidence", "nedt_h", "nedt_v", "tb_diff"]:
    fig = px.histogram(
        df,
        x=col,
        color="target_label",
        barmode="overlay",
        nbins=60,
        opacity=0.65,
        marginal="box",
        title=f"Distribution of {col} by Class"
    )
    fig.show()
    fig.write_html(f"{output_dir}/hist_{col}.html")

"""Violin plots

Comparing the spread and density of important variables across the two classes.
"""

for col in ["tb_h", "tb_v", "incidence", "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"]:
    fig = px.violin(
        df,
        x="target_label",
        y=col,
        color="target_label",
        box=True,
        points="outliers",
        title=f"Violin Plot of {col} by Class"
    )
    fig.show()
    fig.write_html(f"{output_dir}/violin_{col}.html")

"""Correlation heatmap

Analysing linear relationships among the original and engineered features, including correlation with the target.

"""

corr_cols = stats_cols + ["target"]
corr = df[corr_cols].corr()

fig = px.imshow(
    corr,
    text_auto=".2f",
    aspect="auto",
    color_continuous_scale="RdBu_r",
    title="Correlation Heatmap"
)
fig.show()
fig.write_html(f"{output_dir}/correlation_heatmap.html")

"""PCA

Reducing the feature space to two principal components for visual inspection of class separability.
"""

dr_sample = df.sample(n=min(5000, len(df)), random_state=42).copy()

scaler_dr = StandardScaler()
X_scaled_dr = scaler_dr.fit_transform(dr_sample[stats_cols])

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled_dr)

pca_df = pd.DataFrame({
    "PC1": X_pca[:, 0],
    "PC2": X_pca[:, 1],
    "Class": dr_sample["target_label"].values
})

fig = px.scatter(
    pca_df,
    x="PC1",
    y="PC2",
    color="Class",
    title=f"PCA Projection (Explained Variance: {pca.explained_variance_ratio_.sum():.2%})",
    opacity=0.7
)
fig.show()
fig.write_html(f"{output_dir}/pca_projection.html")

"""t-SNE

Exploring local nonlinear structure in the data and identify possible clustering behaviour.
"""

tsne = TSNE(n_components=2, random_state=42, perplexity=30, learning_rate="auto", init="pca")
X_tsne = tsne.fit_transform(X_scaled_dr)

tsne_df = pd.DataFrame({
    "TSNE1": X_tsne[:, 0],
    "TSNE2": X_tsne[:, 1],
    "Class": dr_sample["target_label"].values
})

fig = px.scatter(
    tsne_df,
    x="TSNE1",
    y="TSNE2",
    color="Class",
    title="t-SNE Projection of SMAP Feature Space",
    opacity=0.75
)
fig.show()
fig.write_html(f"{output_dir}/tsne_projection.html")

"""UMAP

Use a modern manifold learning method to visualise structure in the feature space.

"""

umap_model = umap.UMAP(n_components=2, random_state=42)
X_umap = umap_model.fit_transform(X_scaled_dr)

umap_df = pd.DataFrame({
    "UMAP1": X_umap[:, 0],
    "UMAP2": X_umap[:, 1],
    "Class": dr_sample["target_label"].values
})

fig = px.scatter(
    umap_df,
    x="UMAP1",
    y="UMAP2",
    color="Class",
    title="UMAP Projection of SMAP Feature Space",
    opacity=0.75
)
fig.show()
fig.write_html(f"{output_dir}/umap_projection.html")

"""World maps

Display the global spatial distribution of the observations and highlight the geography of affected samples.


"""

plot_sample = df.sample(n=min(10000, len(df)), random_state=42)

fig = px.scatter_geo(
    plot_sample,
    lat="tb_lat",
    lon="tb_lon",
    color="target_label",
    hover_data=["tb_h", "tb_v", "incidence"],
    projection="natural earth",
    title="Global Distribution of SMAP Observations"
)
fig.show()
fig.write_html(f"{output_dir}/world_map_observations.html")

fig = px.scatter_geo(
    plot_sample,
    lat="tb_lat",
    lon="tb_lon",
    color="tb_h",
    hover_data=["target_label", "tb_v", "incidence"],
    projection="natural earth",
    color_continuous_scale="Turbo",
    title="Global Distribution of Horizontal Brightness Temperature (tb_h)"
)
fig.show()
fig.write_html(f"{output_dir}/world_map_tbh.html")

affected_sample = df[df["target"] == 1].sample(
    n=min(8000, len(df[df["target"] == 1])),
    random_state=42
)

fig = px.scatter_geo(
    affected_sample,
    lat="tb_lat",
    lon="tb_lon",
    color="tb_h_roll_kurt",
    hover_data=["tb_h", "tb_v", "tb_diff_roll_kurt"],
    projection="natural earth",
    color_continuous_scale="Inferno",
    title="Global Map of Quality-Affected / Potentially RFI-Affected Observations"
)
fig.show()
fig.write_html(f"{output_dir}/world_map_affected.html")

"""# MODEL DATASET

Define feature sets

Creating two feature sets: a basic set and a richer kurtosis-enhanced set for experimentation.
"""

feature_cols_basic = ["tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v"]

feature_cols_kurt = [
    "tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v",
    "tb_diff", "tb_h_roll_mean", "tb_v_roll_mean",
    "tb_h_roll_std", "tb_v_roll_std",
    "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"
]

X_basic = df[feature_cols_basic].copy()
X_kurt = df[feature_cols_kurt].copy()
y = df["target"].copy()

"""Train/test splits

splitting the data into training and testing subsets while preserving class balance.
"""

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_basic, y, test_size=0.2, random_state=42, stratify=y
)

X_train_k, X_test_k, y_train_k, y_test_k = train_test_split(
    X_kurt, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train_b.shape, X_test_b.shape)
print(X_train_k.shape, X_test_k.shape)

"""# LOGISTIC REGRESSION

Logistic Regression baseline

Trainning a simple interpretable linear baseline model for comparison with advanced methods.
"""

logreg_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

logreg_pipe.fit(X_train_b, y_train_b)
y_pred_lr = logreg_pipe.predict(X_test_b)
y_prob_lr = logreg_pipe.predict_proba(X_test_b)[:, 1]

print(confusion_matrix(y_test_b, y_pred_lr))
print(classification_report(y_test_b, y_pred_lr, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_b, y_prob_lr))

"""# RANDOM FOREST

RF basic

Trainning a nonlinear ensemble baseline on the basic features.
"""

rf_basic = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_basic.fit(X_train_b, y_train_b)
y_pred_rf_basic = rf_basic.predict(X_test_b)
y_prob_rf_basic = rf_basic.predict_proba(X_test_b)[:, 1]

print(confusion_matrix(y_test_b, y_pred_rf_basic))
print(classification_report(y_test_b, y_pred_rf_basic, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_b, y_prob_rf_basic))

"""RF with kurtosis features

Test whether adding engineered features improves Random Forest performance.
"""

rf_kurt = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_kurt.fit(X_train_k, y_train_k)
y_pred_rf_kurt = rf_kurt.predict(X_test_k)
y_prob_rf_kurt = rf_kurt.predict_proba(X_test_k)[:, 1]

print(confusion_matrix(y_test_k, y_pred_rf_kurt))
print(classification_report(y_test_k, y_pred_rf_kurt, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_k, y_prob_rf_kurt))

"""# MLP

Scale for MLP

Standardising the kurtosis-enhanced feature set before neural network training.
"""

scaler_mlp = StandardScaler()
X_train_k_scaled = scaler_mlp.fit_transform(X_train_k)
X_test_k_scaled = scaler_mlp.transform(X_test_k)

"""# MLP model
Training a deep feedforward neural network on the tabular feature set.
"""

tf.random.set_seed(42)

mlp_kurt = Sequential([
    Dense(64, activation="relu", input_shape=(X_train_k_scaled.shape[1],)),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dropout(0.2),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

mlp_kurt.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

early_stop = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

history_mlp_kurt = mlp_kurt.fit(
    X_train_k_scaled, y_train_k,
    validation_split=0.2,
    epochs=30,
    batch_size=128,
    callbacks=[early_stop],
    verbose=1
)

"""Evaluate MLP

Evaluating the MLP on the test data and produce classification metrics.
"""

y_prob_mlp_kurt = mlp_kurt.predict(X_test_k_scaled).ravel()
y_pred_mlp_kurt = (y_prob_mlp_kurt >= 0.5).astype(int)

print(confusion_matrix(y_test_k, y_pred_mlp_kurt))
print(classification_report(y_test_k, y_pred_mlp_kurt, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_k, y_prob_mlp_kurt))

"""MLP learning curves

Visualising the training and validation learning behaviour of the MLP.
"""

plt.figure(figsize=(6,4))
plt.plot(history_mlp_kurt.history["loss"], label="Train Loss")
plt.plot(history_mlp_kurt.history["val_loss"], label="Val Loss")
plt.title("MLP Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

plt.figure(figsize=(6,4))
plt.plot(history_mlp_kurt.history["accuracy"], label="Train Accuracy")
plt.plot(history_mlp_kurt.history["val_accuracy"], label="Val Accuracy")
plt.title("MLP Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

"""# 1D CNN

Build sliding windows

Transforming the time-ordered tabular data into local sequences so a 1D CNN can learn neighbourhood patterns.
"""

seq_features = [
    "tb_h", "tb_v", "incidence", "nedt_h", "nedt_v",
    "tb_diff", "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"
]

seq_df = df[seq_features + ["target"]].copy().reset_index(drop=True)

window_size = 9
X_seq = []
y_seq = []

for i in range(len(seq_df) - window_size + 1):
    window_block = seq_df.iloc[i:i+window_size]
    X_seq.append(window_block[seq_features].values)
    y_seq.append(window_block["target"].iloc[window_size // 2])

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

print("X_seq shape:", X_seq.shape)
print("y_seq shape:", y_seq.shape)

"""Split sequence data

Splitting the sequence dataset into training and testing sets.
"""

X_train_seq, X_test_seq, y_train_seq, y_test_seq = train_test_split(
    X_seq, y_seq, test_size=0.2, random_state=42, stratify=y_seq
)

"""Scale sequence data

Standardising sequence features before CNN training.
"""

n_train, w, f = X_train_seq.shape
n_test = X_test_seq.shape[0]

X_train_seq_2d = X_train_seq.reshape(-1, f)
X_test_seq_2d = X_test_seq.reshape(-1, f)

scaler_seq = StandardScaler()
X_train_seq_scaled = scaler_seq.fit_transform(X_train_seq_2d).reshape(n_train, w, f)
X_test_seq_scaled = scaler_seq.transform(X_test_seq_2d).reshape(n_test, w, f)

print(X_train_seq_scaled.shape, X_test_seq_scaled.shape)

"""1D CNN model

Trainning a sequence-aware convolutional neural network on the sliding-window data.
"""

cnn_1d = Sequential([
    Conv1D(filters=32, kernel_size=3, activation="relu", input_shape=(w, f)),
    MaxPooling1D(pool_size=2),
    Conv1D(filters=64, kernel_size=3, activation="relu"),
    GlobalAveragePooling1D(),
    Dense(32, activation="relu"),
    Dropout(0.3),
    Dense(1, activation="sigmoid")
])

cnn_1d.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

early_stop_cnn = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history_cnn = cnn_1d.fit(
    X_train_seq_scaled, y_train_seq,
    validation_split=0.2,
    epochs=30,
    batch_size=128,
    callbacks=[early_stop_cnn],
    verbose=1
)

"""Evaluate 1D CNN

Assessing the performance of the sequence-aware CNN.
"""

y_prob_cnn = cnn_1d.predict(X_test_seq_scaled).ravel()
y_pred_cnn = (y_prob_cnn >= 0.5).astype(int)

print(confusion_matrix(y_test_seq, y_pred_cnn))
print(classification_report(y_test_seq, y_pred_cnn, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_seq, y_prob_cnn))

"""# XGBOOST

Prepare XGBoost data

Preparing the kurtosis-enhanced feature set for XGBoost and compute the class imbalance ratio.
"""

feature_cols_xgb = feature_cols_kurt.copy()

X_xgb = df[feature_cols_xgb].copy()
y_xgb = df["target"].copy()

X_train_xgb, X_test_xgb, y_train_xgb, y_test_xgb = train_test_split(
    X_xgb, y_xgb, test_size=0.2, random_state=42, stratify=y_xgb
)

neg = (y_train_xgb == 0).sum()
pos = (y_train_xgb == 1).sum()
scale_pos_weight = neg / pos if pos > 0 else 1.0

print("scale_pos_weight:", scale_pos_weight)

"""Baseline XGBoost

Trainning an advanced boosting model as a strong tabular-data benchmark.
"""

xgb_base = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.0,
    reg_lambda=1.0,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

xgb_base.fit(X_train_xgb, y_train_xgb)

y_prob_xgb_base = xgb_base.predict_proba(X_test_xgb)[:, 1]
y_pred_xgb_base = (y_prob_xgb_base >= 0.5).astype(int)

print(confusion_matrix(y_test_xgb, y_pred_xgb_base))
print(classification_report(y_test_xgb, y_pred_xgb_base, digits=4))
print("ROC-AUC:", roc_auc_score(y_test_xgb, y_prob_xgb_base))

"""Cross-validation for XGBoost

Assessing the robustness of the XGBoost model using cross-validation.
"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

xgb_cv_model = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

cv_f1_scores = cross_val_score(
    xgb_cv_model,
    X_train_xgb,
    y_train_xgb,
    cv=cv,
    scoring="f1",
    n_jobs=-1
)

cv_auc_scores = cross_val_score(
    xgb_cv_model,
    X_train_xgb,
    y_train_xgb,
    cv=cv,
    scoring="roc_auc",
    n_jobs=-1
)

print("CV F1 scores:", cv_f1_scores)
print("Mean CV F1:", cv_f1_scores.mean())
print("CV ROC-AUC scores:", cv_auc_scores)
print("Mean CV ROC-AUC:", cv_auc_scores.mean())

"""Tune XGBoost

Optimising XGBoost hyperparameters using grid search.
"""

param_grid_xgb = {
    "n_estimators": [200, 300],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0],
    "min_child_weight": [1, 3],
    "gamma": [0, 0.1]
}

xgb_for_grid = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

grid_xgb = GridSearchCV(
    estimator=xgb_for_grid,
    param_grid=param_grid_xgb,
    scoring="f1",
    cv=3,
    verbose=1,
    n_jobs=-1
)

grid_xgb.fit(X_train_xgb, y_train_xgb)

print("Best params:", grid_xgb.best_params_)
print("Best CV F1:", grid_xgb.best_score_)

"""Evaluate tuned XGBoost

Evaluating the tuned XGBoost model on the held-out test set.
"""

best_xgb = grid_xgb.best_estimator_

y_prob_xgb_tuned = best_xgb.predict_proba(X_test_xgb)[:, 1]
y_pred_xgb_tuned = (y_prob_xgb_tuned >= 0.5).astype(int)

print(confusion_matrix(y_test_xgb, y_pred_xgb_tuned))
print(classification_report(y_test_xgb, y_pred_xgb_tuned, digits=4))
print("Accuracy:", accuracy_score(y_test_xgb, y_pred_xgb_tuned))
print("Balanced Accuracy:", balanced_accuracy_score(y_test_xgb, y_pred_xgb_tuned))
print("Precision:", precision_score(y_test_xgb, y_pred_xgb_tuned, zero_division=0))
print("Recall:", recall_score(y_test_xgb, y_pred_xgb_tuned, zero_division=0))
print("F1:", f1_score(y_test_xgb, y_pred_xgb_tuned, zero_division=0))
print("ROC-AUC:", roc_auc_score(y_test_xgb, y_prob_xgb_tuned))

"""Threshold tuning
Evaluating multiple probability thresholds to identify a better classification operating point
"""

thresholds = np.arange(0.1, 0.91, 0.05)
threshold_results = []

for t in thresholds:
    preds = (y_prob_xgb_tuned >= t).astype(int)
    threshold_results.append({
        "threshold": t,
        "precision": precision_score(y_test_xgb, preds, zero_division=0),
        "recall": recall_score(y_test_xgb, preds, zero_division=0),
        "f1": f1_score(y_test_xgb, preds, zero_division=0),
        "balanced_accuracy": balanced_accuracy_score(y_test_xgb, preds)
    })

threshold_df = pd.DataFrame(threshold_results)
threshold_df

"""Best threshold evaluation

Applying the best-performing threshold and evaluate the model again.
"""

best_threshold = threshold_df.loc[threshold_df["f1"].idxmax(), "threshold"]
print("Best threshold:", best_threshold)

y_pred_xgb_best_thr = (y_prob_xgb_tuned >= best_threshold).astype(int)

print(confusion_matrix(y_test_xgb, y_pred_xgb_best_thr))
print(classification_report(y_test_xgb, y_pred_xgb_best_thr, digits=4))
print("F1:", f1_score(y_test_xgb, y_pred_xgb_best_thr))
print("ROC-AUC:", roc_auc_score(y_test_xgb, y_prob_xgb_tuned))

"""# SHAP

SHAP values

Computing SHAP values for the tuned XGBoost model to explain feature contributions.
"""

explainer = shap.TreeExplainer(best_xgb)
shap_values = explainer.shap_values(X_test_xgb)

print("SHAP values ready.")

"""SHAP summary plots

Visualising global feature importance and contribution patterns using SHAP.
"""

shap.summary_plot(shap_values, X_test_xgb, feature_names=feature_cols_xgb)
shap.summary_plot(shap_values, X_test_xgb, feature_names=feature_cols_xgb, plot_type="bar")

"""SHAP dependence plot

Exploring how one important feature influences model predictions.
"""

shap.dependence_plot("tb_h_roll_kurt", shap_values, X_test_xgb, feature_names=feature_cols_xgb)

"""**# IMPORTANCE and EXPLAINABILITY**

XGBoost built-in importance
Plotting XGBoost’s built-in feature importance scores.
"""

xgb_importance = pd.DataFrame({
    "Feature": feature_cols_xgb,
    "Importance": best_xgb.feature_importances_
}).sort_values("Importance", ascending=False)

fig = px.bar(
    xgb_importance,
    x="Feature",
    y="Importance",
    color="Importance",
    title="XGBoost Built-in Feature Importance"
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()
fig.write_html(f"{output_dir}/xgboost_feature_importance.html")

xgb_importance.to_csv(f"{output_dir}/xgboost_feature_importance.csv", index=False)
xgb_importance

"""Permutation importance

Computing model-agnostic permutation importance for a more robust feature importance analysis.
"""

perm_xgb = permutation_importance(
    best_xgb,
    X_test_xgb,
    y_test_xgb,
    n_repeats=5,
    random_state=42,
    scoring="f1"
)

perm_xgb_df = pd.DataFrame({
    "Feature": feature_cols_xgb,
    "ImportanceMean": perm_xgb.importances_mean,
    "ImportanceStd": perm_xgb.importances_std
}).sort_values("ImportanceMean", ascending=False)

fig = px.bar(
    perm_xgb_df,
    x="Feature",
    y="ImportanceMean",
    error_y="ImportanceStd",
    color="ImportanceMean",
    title="Permutation Importance for XGBoost"
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()
fig.write_html(f"{output_dir}/xgboost_permutation_importance.html")

perm_xgb_df.to_csv(f"{output_dir}/xgboost_permutation_importance.csv", index=False)
perm_xgb_df

"""# ROC / PR / CONFUSION MATRICES

Helper functions

Defining reusable helper functions for confusion matrix plotting and metrics table construction.
"""

def plot_confusion_matrix_simple(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    fig = px.imshow(
        cm,
        text_auto=True,
        color_continuous_scale="Blues",
        x=["Pred Clean", "Pred Affected"],
        y=["True Clean", "True Affected"],
        title=title
    )
    fig.show()

def metric_row(name, y_true, y_pred, y_prob):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob)
    }

"""Confusion matrices

Comparing confusion matrices across all trained models.
"""

plot_confusion_matrix_simple(y_test_b, y_pred_lr, "Confusion Matrix - Logistic Regression")
plot_confusion_matrix_simple(y_test_b, y_pred_rf_basic, "Confusion Matrix - Random Forest Basic")
plot_confusion_matrix_simple(y_test_k, y_pred_rf_kurt, "Confusion Matrix - Random Forest + Kurtosis")
plot_confusion_matrix_simple(y_test_k, y_pred_mlp_kurt, "Confusion Matrix - MLP + Kurtosis")
plot_confusion_matrix_simple(y_test_seq, y_pred_cnn, "Confusion Matrix - 1D CNN")
plot_confusion_matrix_simple(y_test_xgb, y_pred_xgb_best_thr, "Confusion Matrix - Tuned XGBoost")

"""ROC curves
Comparing the ROC performance of all models in a single figure.
"""

plt.figure(figsize=(8,6))

for name, probs, y_true in [
    ("Logistic Regression", y_prob_lr, y_test_b),
    ("RF Basic", y_prob_rf_basic, y_test_b),
    ("RF + Kurtosis", y_prob_rf_kurt, y_test_k),
    ("MLP + Kurtosis", y_prob_mlp_kurt, y_test_k),
    ("1D CNN", y_prob_cnn, y_test_seq),
    ("Tuned XGBoost", y_prob_xgb_tuned, y_test_xgb)
]:
    fpr, tpr, _ = roc_curve(y_true, probs)
    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc_score(y_true, probs):.3f})")

plt.plot([0,1], [0,1], linestyle="--", color="black")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves")
plt.legend()
plt.show()

"""Precision-recall curves"""

plt.figure(figsize=(8,6))

for name, probs, y_true in [
    ("Logistic Regression", y_prob_lr, y_test_b),
    ("RF Basic", y_prob_rf_basic, y_test_b),
    ("RF + Kurtosis", y_prob_rf_kurt, y_test_k),
    ("MLP + Kurtosis", y_prob_mlp_kurt, y_test_k),
    ("1D CNN", y_prob_cnn, y_test_seq),
    ("Tuned XGBoost", y_prob_xgb_tuned, y_test_xgb)
]:
    precision_vals, recall_vals, _ = precision_recall_curve(y_true, probs)
    plt.plot(recall_vals, precision_vals, label=name)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curves")
plt.legend()
plt.show()

"""XGBoost threshold plot"""

fig = px.line(
    threshold_df,
    x="threshold",
    y=["precision", "recall", "f1", "balanced_accuracy"],
    title="Threshold Tuning for XGBoost"
)
fig.show()
fig.write_html(f"{output_dir}/xgboost_threshold_tuning.html")

"""# GEOSPATIAL ERROR ANALYSIS

XGBoost world error map - Showing where correct and incorrect predictions occur geographically.
"""

xgb_test_results = X_test_xgb.copy()
xgb_test_results["true"] = y_test_xgb.values
xgb_test_results["pred"] = y_pred_xgb_best_thr
xgb_test_results["prob"] = y_prob_xgb_tuned
xgb_test_results["error_type"] = np.where(
    xgb_test_results["true"] == xgb_test_results["pred"],
    "Correct",
    "Misclassified"
)

error_sample = xgb_test_results.sample(n=min(10000, len(xgb_test_results)), random_state=42)

fig = px.scatter_geo(
    error_sample,
    lat="tb_lat",
    lon="tb_lon",
    color="error_type",
    hover_data=["true", "pred", "prob"],
    projection="natural earth",
    title="World Map of XGBoost Prediction Errors"
)
fig.show()
fig.write_html(f"{output_dir}/world_map_xgboost_errors.html")

"""# FINAL COMPARISON TABLE

Build comparison table

Summarising the performance of all models in one final comparison table.
"""

results_all = pd.DataFrame([
    metric_row("Logistic Regression", y_test_b, y_pred_lr, y_prob_lr),
    metric_row("RF Basic", y_test_b, y_pred_rf_basic, y_prob_rf_basic),
    metric_row("RF + Kurtosis", y_test_k, y_pred_rf_kurt, y_prob_rf_kurt),
    metric_row("MLP + Kurtosis", y_test_k, y_pred_mlp_kurt, y_prob_mlp_kurt),
    metric_row("1D CNN", y_test_seq, y_pred_cnn, y_prob_cnn),
    metric_row("Tuned XGBoost", y_test_xgb, y_pred_xgb_best_thr, y_prob_xgb_tuned)
])

results_all = results_all.sort_values("F1", ascending=False).reset_index(drop=True)
results_all.to_csv(f"{output_dir}/final_model_comparison.csv", index=False)
results_all

"""Model comparison bar chart

Visualising model performance across multiple evaluation metrics.
"""

fig = px.bar(
    results_all.melt(id_vars="Model", var_name="Metric", value_name="Score"),
    x="Model",
    y="Score",
    color="Metric",
    barmode="group",
    title="Model Comparison Across Metrics"
)
fig.update_layout(xaxis_tickangle=-30)
fig.show()
fig.write_html(f"{output_dir}/model_comparison_metrics.html")

"""Radar chart

Presenting a compact visual summary of overall model performance.
"""

metrics_for_radar = ["Accuracy", "Balanced Accuracy", "Precision", "Recall", "F1", "ROC-AUC"]

fig = go.Figure()

for _, row in results_all.iterrows():
    fig.add_trace(go.Scatterpolar(
        r=[row[m] for m in metrics_for_radar],
        theta=metrics_for_radar,
        fill='toself',
        name=row["Model"]
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    title="Radar Chart of Model Performance"
)

fig.show()
fig.write_html(f"{output_dir}/model_radar_chart.html")

"""# Save outputs"""

df.to_csv(f"{output_dir}/final_dataset_for_analysis.csv", index=False)
threshold_df.to_csv(f"{output_dir}/xgboost_threshold_results.csv", index=False)
xgb_test_results.to_csv(f"{output_dir}/xgboost_test_predictions.csv", index=False)

print("All major outputs saved to:", output_dir)

"""# Additional - Experiments

subset experiment

Subset experiment setup
"""

subset_sizes = [0.10, 0.25, 0.50, 1.00]

def metric_row_subset(name, subset_size, y_true, y_pred, y_prob):
    return {
        "Model": name,
        "SubsetSize": subset_size,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob)
    }

"""Prepare a common subset function"""

def stratified_subset(X, y, frac, random_state=42):
    X_sub, _, y_sub, _ = train_test_split(
        X, y,
        train_size=frac,
        random_state=random_state,
        stratify=y
    )
    return X_sub, y_sub



from google.colab import drive
drive.mount('/content/gdrive')

import os

print(os.path.exists("/content/gdrive/MyDrive"))
print(os.listdir("/content/gdrive/MyDrive")[:20])

import os

for root, dirs, files in os.walk("/content/gdrive/MyDrive"):
    for f in files:
        if f.endswith(".h5") and "SMAP" in f:
            print(os.path.join(root, f))

file_path = "/content/gdrive/MyDrive/AML/Data/SMAP_L1B_TB_59906_A_20260419T160238_R19240_001.h5"

"""Subset experiment for tabular models"""

# ============================================================
# FULL SELF-CONTAINED SUBSET EXPERIMENT
# Mounts Google Drive -> finds SMAP file -> rebuilds df
# -> recreates train/test splits -> runs subset testing
# ============================================================

import os
import warnings
warnings.filterwarnings("ignore")

import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import tensorflow as tf
import xgboost as xgb

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, GlobalAveragePooling1D
from tensorflow.keras.callbacks import EarlyStopping

# -----------------------------
# 1) MOUNT GOOGLE DRIVE
# -----------------------------
try:
    from google.colab import drive
    drive.mount('/content/gdrive')
    ROOT_DIR = "/content/gdrive/MyDrive"
except Exception as e:
    print("Google Drive mount failed or not running in Colab.")
    print("Error:", e)
    ROOT_DIR = "."

print("Using ROOT_DIR:", ROOT_DIR)

# -----------------------------
# 2) FIND THE SMAP .h5 FILE
# -----------------------------
target_name = "SMAP_L1B_TB_59906_A_20260419T160238_R19240_001.h5"

matches = []
for root, dirs, files in os.walk(ROOT_DIR):
    if target_name in files:
        matches.append(os.path.join(root, target_name))

if len(matches) == 0:
    # broader search if exact file name not found
    for root, dirs, files in os.walk(ROOT_DIR):
        for f in files:
            if f.endswith(".h5") and "SMAP" in f:
                matches.append(os.path.join(root, f))

print("\nFound matches:")
for m in matches:
    print(m)

if len(matches) == 0:
    raise FileNotFoundError(
        "No SMAP .h5 file found in Google Drive. "
        "Please check the file name or upload/move the file into MyDrive."
    )

# Use the first match automatically
file_path = matches[0]
print("\nUsing file:", file_path)

# -----------------------------
# 3) SET OUTPUT DIRECTORY
# -----------------------------
output_dir = os.path.join(ROOT_DIR, "AML", "Outputs")
os.makedirs(output_dir, exist_ok=True)
print("Output directory:", output_dir)

# -----------------------------
# 4) READ HDF5 VARIABLES
# -----------------------------
with h5py.File(file_path, "r") as f:
    tb_h = f["Brightness_Temperature/tb_h"][:]
    tb_v = f["Brightness_Temperature/tb_v"][:]
    tb_lat = f["Brightness_Temperature/tb_lat"][:]
    tb_lon = f["Brightness_Temperature/tb_lon"][:]
    incidence = f["Brightness_Temperature/earth_boresight_incidence"][:]
    nedt_h = f["Brightness_Temperature/nedt_h"][:]
    nedt_v = f["Brightness_Temperature/nedt_v"][:]
    qual_flag_h = f["Brightness_Temperature/tb_qual_flag_h"][:]
    tb_time_seconds = f["Brightness_Temperature/tb_time_seconds"][:]

# -----------------------------
# 5) BUILD DATAFRAME
# -----------------------------
df = pd.DataFrame({
    "tb_h": np.ravel(tb_h),
    "tb_v": np.ravel(tb_v),
    "tb_lat": np.ravel(tb_lat),
    "tb_lon": np.ravel(tb_lon),
    "incidence": np.ravel(incidence),
    "nedt_h": np.ravel(nedt_h),
    "nedt_v": np.ravel(nedt_v),
    "qual_flag_h": np.ravel(qual_flag_h),
    "tb_time_seconds": np.ravel(tb_time_seconds)
})

print("\nInitial df shape:", df.shape)

# -----------------------------
# 6) CLEAN DATA
# -----------------------------
df = df.replace([np.inf, -np.inf], np.nan)

for col in ["tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v", "tb_time_seconds"]:
    df.loc[np.abs(df[col]) > 1e10, col] = np.nan

df = df.dropna().copy()

df = df[
    (df["tb_lat"] >= -90) & (df["tb_lat"] <= 90) &
    (df["tb_lon"] >= -180) & (df["tb_lon"] <= 180)
].copy()

df = df.sort_values("tb_time_seconds").reset_index(drop=True)

# -----------------------------
# 7) TARGET + FEATURE ENGINEERING
# -----------------------------
df["target"] = (df["qual_flag_h"] != 0).astype(int)
df["target_label"] = df["target"].map({0: "Clean", 1: "Affected"})

window = 9
df["tb_diff"] = df["tb_h"] - df["tb_v"]

df["tb_h_roll_mean"] = df["tb_h"].rolling(window=window, center=True).mean()
df["tb_v_roll_mean"] = df["tb_v"].rolling(window=window, center=True).mean()

df["tb_h_roll_std"] = df["tb_h"].rolling(window=window, center=True).std()
df["tb_v_roll_std"] = df["tb_v"].rolling(window=window, center=True).std()

df["tb_h_roll_kurt"] = df["tb_h"].rolling(window=window, center=True).kurt()
df["tb_v_roll_kurt"] = df["tb_v"].rolling(window=window, center=True).kurt()
df["tb_diff_roll_kurt"] = df["tb_diff"].rolling(window=window, center=True).kurt()

df = df.dropna().reset_index(drop=True)

print("Cleaned df shape:", df.shape)
print(df["target"].value_counts())

# Save rebuilt dataset
df.to_csv(os.path.join(output_dir, "rebuilt_df_for_subset_experiment.csv"), index=False)

# -----------------------------
# 8) FEATURE SETS
# -----------------------------
feature_cols_basic = ["tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v"]

feature_cols_kurt = [
    "tb_h", "tb_v", "tb_lat", "tb_lon", "incidence", "nedt_h", "nedt_v",
    "tb_diff", "tb_h_roll_mean", "tb_v_roll_mean",
    "tb_h_roll_std", "tb_v_roll_std",
    "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"
]

X_basic = df[feature_cols_basic].copy()
X_kurt = df[feature_cols_kurt].copy()
y = df["target"].copy()

# -----------------------------
# 9) TRAIN / TEST SPLITS
# -----------------------------
X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    X_basic, y, test_size=0.2, random_state=42, stratify=y
)

X_train_k, X_test_k, y_train_k, y_test_k = train_test_split(
    X_kurt, y, test_size=0.2, random_state=42, stratify=y
)

X_train_xgb, X_test_xgb, y_train_xgb, y_test_xgb = train_test_split(
    X_kurt, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# 10) CNN SEQUENCE DATA
# -----------------------------
seq_features = [
    "tb_h", "tb_v", "incidence", "nedt_h", "nedt_v",
    "tb_diff", "tb_h_roll_kurt", "tb_v_roll_kurt", "tb_diff_roll_kurt"
]

seq_df = df[seq_features + ["target"]].copy().reset_index(drop=True)

window_size = 9
X_seq = []
y_seq = []

for i in range(len(seq_df) - window_size + 1):
    block = seq_df.iloc[i:i+window_size]
    X_seq.append(block[seq_features].values)
    y_seq.append(block["target"].iloc[window_size // 2])

X_seq = np.array(X_seq)
y_seq = np.array(y_seq)

X_train_seq, X_test_seq, y_train_seq, y_test_seq = train_test_split(
    X_seq, y_seq, test_size=0.2, random_state=42, stratify=y_seq
)

n_train, w, f = X_train_seq.shape
n_test = X_test_seq.shape[0]

X_train_seq_2d = X_train_seq.reshape(-1, f)
X_test_seq_2d = X_test_seq.reshape(-1, f)

scaler_seq = StandardScaler()
X_train_seq_scaled = scaler_seq.fit_transform(X_train_seq_2d).reshape(n_train, w, f)
X_test_seq_scaled = scaler_seq.transform(X_test_seq_2d).reshape(n_test, w, f)

# -----------------------------
# 11) HELPERS
# -----------------------------
subset_sizes = [0.10, 0.25, 0.50, 1.00]

def metric_row_subset(name, subset_size, y_true, y_pred, y_prob):
    return {
        "Model": name,
        "SubsetSize": subset_size,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_true, y_prob)
    }

def stratified_subset(X, y, frac, random_state=42):
    if np.isclose(frac, 1.0) or frac >= 1.0:
        return X.copy(), y.copy()

    X_sub, _, y_sub, _ = train_test_split(
        X, y,
        train_size=frac,
        random_state=random_state,
        stratify=y
    )
    return X_sub, y_sub

# -----------------------------
# 12) SUBSET EXPERIMENT - TABULAR MODELS
# -----------------------------
subset_results = []

for frac in subset_sizes:
    print(f"\n===== Running subset size: {int(frac*100)}% =====")

    # Logistic Regression
    X_sub_lr, y_sub_lr = stratified_subset(X_train_b, y_train_b, frac)
    print("LR subset:", X_sub_lr.shape)

    logreg_sub = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(max_iter=1000, class_weight="balanced"))
    ])
    logreg_sub.fit(X_sub_lr, y_sub_lr)
    y_pred_lr_sub = logreg_sub.predict(X_test_b)
    y_prob_lr_sub = logreg_sub.predict_proba(X_test_b)[:, 1]
    subset_results.append(metric_row_subset(
        "Logistic Regression", frac, y_test_b, y_pred_lr_sub, y_prob_lr_sub
    ))

    # Random Forest + Kurtosis
    X_sub_rf, y_sub_rf = stratified_subset(X_train_k, y_train_k, frac)
    print("RF subset:", X_sub_rf.shape)

    rf_sub = RandomForestClassifier(
        n_estimators=200,
        max_depth=12,
        min_samples_split=10,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )
    rf_sub.fit(X_sub_rf, y_sub_rf)
    y_pred_rf_sub = rf_sub.predict(X_test_k)
    y_prob_rf_sub = rf_sub.predict_proba(X_test_k)[:, 1]
    subset_results.append(metric_row_subset(
        "RF + Kurtosis", frac, y_test_k, y_pred_rf_sub, y_prob_rf_sub
    ))

    # MLP + Kurtosis
    X_sub_mlp, y_sub_mlp = stratified_subset(X_train_k, y_train_k, frac)
    print("MLP subset:", X_sub_mlp.shape)

    scaler_sub_mlp = StandardScaler()
    X_sub_mlp_scaled = scaler_sub_mlp.fit_transform(X_sub_mlp)
    X_test_k_scaled_sub = scaler_sub_mlp.transform(X_test_k)

    tf.random.set_seed(42)
    mlp_sub = Sequential([
        Dense(64, activation="relu", input_shape=(X_sub_mlp_scaled.shape[1],)),
        Dropout(0.3),
        Dense(32, activation="relu"),
        Dropout(0.2),
        Dense(16, activation="relu"),
        Dense(1, activation="sigmoid")
    ])
    mlp_sub.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

    early_stop_sub = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

    mlp_sub.fit(
        X_sub_mlp_scaled, y_sub_mlp,
        validation_split=0.2,
        epochs=20,
        batch_size=128,
        callbacks=[early_stop_sub],
        verbose=0
    )

    y_prob_mlp_sub = mlp_sub.predict(X_test_k_scaled_sub, verbose=0).ravel()
    y_pred_mlp_sub = (y_prob_mlp_sub >= 0.5).astype(int)
    subset_results.append(metric_row_subset(
        "MLP + Kurtosis", frac, y_test_k, y_pred_mlp_sub, y_prob_mlp_sub
    ))

    # XGBoost
    X_sub_xgb, y_sub_xgb = stratified_subset(X_train_xgb, y_train_xgb, frac)
    print("XGB subset:", X_sub_xgb.shape)

    neg_sub = (y_sub_xgb == 0).sum()
    pos_sub = (y_sub_xgb == 1).sum()
    scale_pos_weight_sub = neg_sub / pos_sub if pos_sub > 0 else 1.0

    xgb_sub = xgb.XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight_sub,
        random_state=42,
        n_jobs=-1
    )
    xgb_sub.fit(X_sub_xgb, y_sub_xgb)
    y_prob_xgb_sub = xgb_sub.predict_proba(X_test_xgb)[:, 1]
    y_pred_xgb_sub = (y_prob_xgb_sub >= 0.5).astype(int)
    subset_results.append(metric_row_subset(
        "Tuned XGBoost", frac, y_test_xgb, y_pred_xgb_sub, y_prob_xgb_sub
    ))

# -----------------------------
# 13) SUBSET EXPERIMENT - CNN
# -----------------------------
for frac in subset_sizes:
    print(f"\n===== Running CNN subset size: {int(frac*100)}% =====")

    X_sub_seq, y_sub_seq = stratified_subset(X_train_seq_scaled, y_train_seq, frac)
    print("CNN subset:", X_sub_seq.shape)

    tf.random.set_seed(42)
    cnn_sub = Sequential([
        Conv1D(filters=32, kernel_size=3, activation="relu", input_shape=(X_sub_seq.shape[1], X_sub_seq.shape[2])),
        MaxPooling1D(pool_size=2),
        Conv1D(filters=64, kernel_size=3, activation="relu"),
        GlobalAveragePooling1D(),
        Dense(32, activation="relu"),
        Dropout(0.3),
        Dense(1, activation="sigmoid")
    ])
    cnn_sub.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

    early_stop_cnn_sub = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

    cnn_sub.fit(
        X_sub_seq, y_sub_seq,
        validation_split=0.2,
        epochs=20,
        batch_size=128,
        callbacks=[early_stop_cnn_sub],
        verbose=0
    )

    y_prob_cnn_sub = cnn_sub.predict(X_test_seq_scaled, verbose=0).ravel()
    y_pred_cnn_sub = (y_prob_cnn_sub >= 0.5).astype(int)
    subset_results.append(metric_row_subset(
        "1D CNN", frac, y_test_seq, y_pred_cnn_sub, y_prob_cnn_sub
    ))

# -----------------------------
# 14) RESULTS TABLE
# -----------------------------
subset_results_df = pd.DataFrame(subset_results)
subset_results_df["SubsetPercent"] = (subset_results_df["SubsetSize"] * 100).astype(int)
subset_results_df["SubsetLabel"] = subset_results_df["SubsetPercent"].astype(str) + "%"
subset_results_df = subset_results_df.sort_values(["Model", "SubsetSize"]).reset_index(drop=True)

print("\nSubset experiment results:")
display(subset_results_df)

subset_results_df.to_csv(os.path.join(output_dir, "subset_experiment_results.csv"), index=False)

# -----------------------------
# 15) PLOTS
# -----------------------------
fig = px.line(
    subset_results_df,
    x="SubsetPercent",
    y="F1",
    color="Model",
    markers=True,
    title="Subset Experiment: F1 Score vs Training Set Size"
)
fig.show()
fig.write_html(os.path.join(output_dir, "subset_f1_vs_size.html"))

fig = px.line(
    subset_results_df,
    x="SubsetPercent",
    y="ROC-AUC",
    color="Model",
    markers=True,
    title="Subset Experiment: ROC-AUC vs Training Set Size"
)
fig.show()
fig.write_html(os.path.join(output_dir, "subset_auc_vs_size.html"))

pivot_f1 = subset_results_df.pivot(index="Model", columns="SubsetPercent", values="F1")
fig = px.imshow(
    pivot_f1,
    text_auto=".3f",
    aspect="auto",
    color_continuous_scale="Viridis",
    title="Subset Experiment Heatmap: F1 Scores"
)
fig.show()
fig.write_html(os.path.join(output_dir, "subset_f1_heatmap.html"))

# -----------------------------
# 16) SUMMARY
# -----------------------------
subset_summary = subset_results_df.groupby("Model")[[
    "Accuracy", "Balanced Accuracy", "Precision", "Recall", "F1", "ROC-AUC"
]].mean().sort_values("F1", ascending=False)

print("\nAverage performance across subset sizes:")
display(subset_summary)

subset_summary.to_csv(os.path.join(output_dir, "subset_experiment_summary.csv"))

print("\nSubset experiment completed successfully.")
print("Outputs saved to:", output_dir)

"""Subset experiment for 1D CNN"""

for frac in subset_sizes:
    print(f"\n===== Running CNN subset size: {int(frac*100)}% =====")

    X_sub_seq, y_sub_seq = stratified_subset(X_train_seq_scaled, y_train_seq, frac)

    tf.random.set_seed(42)
    cnn_sub = Sequential([
        Conv1D(filters=32, kernel_size=3, activation="relu", input_shape=(X_sub_seq.shape[1], X_sub_seq.shape[2])),
        MaxPooling1D(pool_size=2),
        Conv1D(filters=64, kernel_size=3, activation="relu"),
        GlobalAveragePooling1D(),
        Dense(32, activation="relu"),
        Dropout(0.3),
        Dense(1, activation="sigmoid")
    ])

    cnn_sub.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    early_stop_cnn_sub = EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    )

    cnn_sub.fit(
        X_sub_seq, y_sub_seq,
        validation_split=0.2,
        epochs=20,
        batch_size=128,
        callbacks=[early_stop_cnn_sub],
        verbose=0
    )

    y_prob_cnn_sub = cnn_sub.predict(X_test_seq_scaled, verbose=0).ravel()
    y_pred_cnn_sub = (y_prob_cnn_sub >= 0.5).astype(int)

    subset_results.append(metric_row_subset(
        "1D CNN", frac, y_test_seq, y_pred_cnn_sub, y_prob_cnn_sub
    ))

"""Build subset results table"""

subset_results_df = pd.DataFrame(subset_results)
subset_results_df["SubsetPercent"] = (subset_results_df["SubsetSize"] * 100).astype(int)

subset_results_df = subset_results_df.sort_values(["Model", "SubsetSize"]).reset_index(drop=True)
subset_results_df.to_csv(f"{output_dir}/subset_experiment_results.csv", index=False)

subset_results_df

"""Plot F1 vs subset size"""

fig = px.line(
    subset_results_df,
    x="SubsetPercent",
    y="F1",
    color="Model",
    markers=True,
    title="Subset Experiment: F1 Score vs Training Set Size"
)
fig.update_layout(xaxis_title="Training Subset Size (%)", yaxis_title="F1 Score")
fig.show()

fig.write_html(f"{output_dir}/subset_f1_vs_size.html")

"""Plot ROC-AUC vs subset size"""

fig = px.line(
    subset_results_df,
    x="SubsetPercent",
    y="ROC-AUC",
    color="Model",
    markers=True,
    title="Subset Experiment: ROC-AUC vs Training Set Size"
)
fig.update_layout(xaxis_title="Training Subset Size (%)", yaxis_title="ROC-AUC")
fig.show()

fig.write_html(f"{output_dir}/subset_auc_vs_size.html")

"""Heatmap of subset experiment results

Providing a summary view of F1 performance across models and subset sizes.

Best model stability summary
Summarising which models remain strongest as data availability changes.
"""

pivot_f1 = subset_results_df.pivot_table(
    index="Model",
    columns="SubsetPercent",
    values="F1",
    aggfunc="mean"
)

fig = px.imshow(
    pivot_f1,
    text_auto=".3f",
    aspect="auto",
    color_continuous_scale="Viridis",
    title="Subset Experiment Heatmap: F1 Scores"
)
fig.show()

fig.write_html(f"{output_dir}/subset_f1_heatmap.html")

subset_summary = subset_results_df.groupby("Model")[["Accuracy", "Balanced Accuracy", "Precision", "Recall", "F1", "ROC-AUC"]].mean()
subset_summary = subset_summary.sort_values("F1", ascending=False)

subset_summary.to_csv(f"{output_dir}/subset_experiment_summary.csv")
subset_summary